#!/usr/bin/python3
# Test like so: cat test.mime | /usr/libexec/postfix/kolab_contentfilter_cli -f admin@kolab.local -- noreply@kolab.local
import sys
import logging
import requests
from subprocess import Popen, PIPE

EX_SUCCESS = 0
# Postfix will bounce and not retry
EX_UNAVAILABLE = 69
# Postfix will retry via deferred queue
EX_TEMPFAIL = 75


def get_args():
    try:
        logging.debug("ARGV : %r" % sys.argv)
        cli_from = sys.argv[2].lower()
        cli_to = sys.argv[4:]
        return (cli_from, cli_to)
    except Exception:
        logging.error("Invalid to / from : %r" % sys.argv)
        sys.exit(EX_UNAVAILABLE)


def reinject(content, sender, to):
    command = ["/usr/sbin/sendmail", "-G", "-i", "-f", sender] + to
    stdout = ''
    stderr = ''
    retval = 0
    try:
        process = Popen(command, stdin=PIPE)
        (stdout, stderr) = process.communicate(content.encode())
        retval = process.wait()
        if retval == 0:
            logging.debug("Mail resent via sendmail, stdout: %s, stderr: %s" % (stdout, stderr))
            return EX_SUCCESS
        else:
            raise Exception("retval not zero - %s" % retval)
    except Exception as e:
        print(f"Error re-injecting via {command}")
        logging.error("Exception while re-injecting mail: %s -- stdout:%s, stderr:%s, retval: %s" % (e, stdout, stderr, retval))
        logging.error(f"Commandline used: {command}")
        return EX_TEMPFAIL


def logContent(content):
    content = content.replace("\r", "CR")
    content = content.replace("\n", "LF\n")
    logging.info(content)


if __name__ == "__main__":
    (cli_from, cli_to) = get_args()

    logging.root.handlers = []
    logging.basicConfig(level=logging.WARNING,
                        format='%(asctime)s %(levelname)s %(message)s',
                        filename='/var/log/kolab/postfix-content-filter.log',
                        filemode='a')

    content = sys.stdin.read()

    # To debug what we actually get in terms of line endings
    # I've tested sys.stdin.buffer, but it seems we get LF line endings from postfix
    # logContent(content)

    # Normalize to CRLF line endings.
    content = content.replace('\r\n', '\n')
    content = content.replace('\n', '\r\n')

    try:
        to = ','.join(cli_to)
        request_url = f"SERVICES_HOST/api/webhooks/policy/mail/filter?recipient={to}&sender={cli_from}"
        logging.debug(request_url)
        response = requests.post(
            request_url,
            data=content,
            verify=True
        )

        if response.status_code != 200:
            logging.warning(f"Invalid status code {response.status_code}.")
            print(f"Invalid status code {response.status_code}")
            sys.exit(EX_TEMPFAIL)

        result = response.headers['X-Kolab-Mailfilter-Action']

        if result == 'ACCEPT_EMPTY':
            logging.debug("No changes requested, reinjecting original content.")
            print("Unmodified email")
        elif result == 'ACCEPT':
            logging.debug("Updating content.")
            print("Modified email")
            content = response.text
        elif result == 'REJECT':
            logging.debug("Rejecting email.")
            print("Rejecting email")
            sys.exit(EX_UNAVAILABLE)
        elif result == 'DISCARD':
            logging.debug("Ignoring email.")
            print("Dropping email")
            sys.exit(EX_SUCCESS)
        else:
            logging.warning(f"Unknown X-Kolab-Mailfilter-Action {result}.")
            print(f"Unknown X-Kolab-Mailfilter status {result}")
            sys.exit(EX_TEMPFAIL)

    # pylint: disable=broad-except
    except Exception as e:
        logging.warning(f"Request failed: {request_url}, {str(e)}")
        print(f"Request failed: {request_url}, {str(e)}")
        sys.exit(EX_TEMPFAIL)

    content = content.replace('\r\n', '\n')
    sys.exit(reinject(content, cli_from, cli_to))
