create_arbitrary_users() {
    mysql $mysql_flags << EOF
ALTER USER IF EXISTS $DB_HKCCP_USERNAME@'%' IDENTIFIED BY '$DB_HKCCP_PASSWORD';
ALTER USER IF EXISTS $DB_HKCCP_USERNAME@'127.0.0.1' IDENTIFIED BY '$DB_HKCCP_PASSWORD';
ALTER USER IF EXISTS $DB_KOLAB_USERNAME@'%' IDENTIFIED BY '$DB_KOLAB_PASSWORD';
ALTER USER IF EXISTS $DB_KOLAB_USERNAME@'127.0.0.1' IDENTIFIED BY '$DB_KOLAB_PASSWORD';
ALTER USER IF EXISTS $DB_RC_USERNAME@'%' IDENTIFIED BY '$DB_RC_PASSWORD';
ALTER USER IF EXISTS $DB_RC_USERNAME@'127.0.0.1' IDENTIFIED BY '$DB_RC_PASSWORD';
FLUSH PRIVILEGES;
EOF

}

if ! [ -v MYSQL_RUNNING_AS_SLAVE ]; then
    create_arbitrary_users
fi
